query Panes($viewerName: String!) {
  viewer(where: { name: $viewerName }) {
    activePanes {
      id
      rowStart
      rowSpan
      colStart
      colSpan
      content {
        title
        url
      }
    }
  }
}
